{{- range $name, $inst := .Values.instances }}
{{- if $inst.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quill.fullname" $ }}-{{ $name }}-secrets
  labels:
    {{- include "quill.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $value := $inst.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
